version: '3'
services:
  postgres:
    container_name: "smart-wallet-psql"
    image: "postgres:latest"
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=zinid
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=smart-wallet

volumes:
  db-data:
    driver: local